services:
  arm-none-eabi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arm-none-eabi-dev
    network_mode: host

    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "tail -f /dev/null"